const steps=[
["Raw Grid Data","Historical hourly records","Approximately ten years of timestamped MW, MVAR, metadata, and data-quality information.","The workflow identifies source files and extracts the records required for analysis.","A complete collection of raw historical operating records.","Establishes the source material needed to understand long-term system behavior."],
["Parse & Clean","Standardized, validated values","Raw records with inconsistent names, formats, and occasional invalid telemetry.","Timestamps and measurements are parsed, names are standardized, and missing or impossible values are handled.","Consistent, analysis-ready records.","Prevents poor-quality data from distorting statistics, visualizations, and conclusions."],
["Searchable Database","Structured historical records","Cleaned records and standardized component metadata.","Records are organized and imported into a structured database for repeatable retrieval.","A searchable historical data source.","Reduces time spent manually locating and combining years of operating information."],
["Statistical Analysis","Patterns, ranges, and behavior","Structured component-level historical data.","The workflow calculates averages, extrema, standard deviation, skewness, and power-factor behavior.","Comparable statistical summaries for each component and period.","Helps engineers identify typical behavior, variation, and unusual conditions."],
["Visual Reports","Automated engineering plots","Historical records and calculated statistics.","Automated reports generate time-series plots, rolling averages, seasonal overlays, markers, and event views.","Clear visual summaries of long-term behavior.","Makes patterns easier to interpret and communicate during engineering studies."],
["Engineering Decisions","Faster, defensible insight","Clean data, statistics, and visual reports.","Engineers apply the results to studies, modeling, planning, compliance, and ad hoc investigations.","Repeatable evidence that supports technical decisions.","Shortens analysis time and improves consistency across future engineering work."]
];
let current=0;const wrap=document.getElementById("workflowSteps");
steps.forEach((s,i)=>{const b=document.createElement("button");b.innerHTML=`<span class="num">${String(i+1).padStart(2,"0")}</span><span class="title">${s[0]}</span><span class="caption">${s[1]}</span>`;b.onclick=()=>show(i);wrap.appendChild(b)});
const dots=document.getElementById("dots");steps.forEach(()=>{const d=document.createElement("span");d.className="dot";dots.appendChild(d)});
function show(i){current=(i+steps.length)%steps.length;const s=steps[current];detailNumber.textContent=`STAGE ${String(current+1).padStart(2,"0")}`;detailTitle.textContent=s[0];detailInput.textContent=s[2];detailProcess.textContent=s[3];detailOutput.textContent=s[4];detailValue.textContent=s[5];document.querySelectorAll(".workflow button").forEach((e,j)=>e.classList.toggle("active",j===current));document.querySelectorAll(".dot").forEach((e,j)=>e.classList.toggle("active",j===current))}
prev.onclick=()=>show(current-1);next.onclick=()=>show(current+1);year.textContent=new Date().getFullYear();show(0);